# Generated by Django 4.0.4 on 2022-05-20 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0002_rename_initialstocks_initialstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='deliveredAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='command',
            name='retour',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='sortie',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='stockCourant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='initialstock',
            name='deleveredAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='initialstock',
            name='stockInitial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='deleveredAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
